version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: book-crud-app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/mybookdb
    command: gunicorn app:app --bind 0.0.0.0:5000

volumes:
  mongodb_data:
